on:
  push:
    branches:
      - godot-4.x
    paths:
      - '**.h'
      - '**.cpp'
jobs:
  linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Submodules
        run: git submodule update --init --recursive
      - name: Build binaries
        run: |
          sudo apt-get update
          sudo apt-get install scons
          sudo apt-get install gcc-multilib
          sudo apt-get install g++-multilib
          python3 build.py platform=linux
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: bin_linux
          path: ./addons/godot-flexbox/bin

  android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Submodules
        run: git submodule update --init --recursive
      - name: Build binaries
        run: |
          sudo apt-get install scons
          python3 build.py platform=android
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: bin_android
          path: ./addons/godot-flexbox/bin

  macos:
    name: Build for macOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Submodules
        run: git submodule update --init --recursive
      - name: Build binaries
        run: |
          brew install scons
          python3 build.py platform=macos
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: bin_macos
          path: ./addons/godot-flexbox/bin

  ios:
    name: Build for iOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Submodules
        run: git submodule update --init --recursive
      - name: Build binaries
        run: |
          brew install scons
          python3 build.py platform=ios
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: bin_ios
          path: ./addons/godot-flexbox/bin

  windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Submodules
        run: git submodule update --init --recursive
      - name: Build binaries
        run: |
          python -m pip install scons
          python build.py platform=windows
        shell: cmd
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: bin_windows
          path: ./addons/godot-flexbox/bin

  web:
    name: Build for Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Submodules
        run: git submodule update --init --recursive
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v12
        with:
          version: 3.1.18
          actions-cache-folder: './emsdk'
      - name: Build binaries
        run: |
          sudo apt-get install scons
          python3 build.py platform=web
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: bin_web
          path: ./addons/godot-flexbox/bin

  merge:
    name: Merge 
    runs-on: ubuntu-latest
    needs: [linux, android, macos, ios, windows, web]
    steps:
      - uses: actions/checkout@v3

      - name: Download Linux binaries
        uses: actions/download-artifact@v1
        with:
          name: bin_linux

      - name: Download Android binaries
        uses: actions/download-artifact@v1
        with:
          name: bin_android

      - name: Download macOS binaries
        uses: actions/download-artifact@v1
        with:
          name: bin_macos

      - name: Download iOS binaries
        uses: actions/download-artifact@v1
        with:
          name: bin_ios

      - name: Download Windows binaries
        uses: actions/download-artifact@v1
        with:
          name: bin_windows

      - name: Download web binaries
        uses: actions/download-artifact@v1
        with:
          name: bin_web

      - name: Copy binaries
        run: |
          mkdir ./addons/godot-flexbox/bin
          cp -r bin_linux/linux ./addons/godot-flexbox/bin/
          cp -r bin_android/android ./addons/godot-flexbox/bin/
          cp -r bin_macos/macos ./addons/godot-flexbox/bin/
          cp -r bin_ios/ios ./addons/godot-flexbox/bin/
          cp -r bin_windows/windows ./addons/godot-flexbox/bin/
          cp -r bin_web/web ./addons/godot-flexbox/bin/

      - name: Upload built package
        uses: actions/upload-artifact@v3
        with:
          name: addons
          path: ./addons
